// .design-sync/previews/LocaleRow.tsx
import * as React from 'react';
import { LocaleRow } from '@panomc/panel-ui';

const Table = ({ children }: { children: React.ReactNode }) => (
  <div className="card">
    <style>{`.ds-rt > [data-pano-component]{display:table-row-group;}`}</style>
    <div className="table-responsive">
      <table className="table table-hover align-middle mb-0 ds-rt">
        <thead>
          <tr>
            {['', 'Name', 'Code', 'date-fns Code', 'Derivatives', 'Defined By'].map((c, i) => (
              <th key={i} scope="col" className="text-nowrap">
                {c}
              </th>
            ))}
          </tr>
        </thead>
        {children}
      </table>
    </div>
  </div>
);

export const SystemLocale = () => (
  <Table>
    <LocaleRow
      index={0}
      locale={{
        id: 1,
        name: 'English',
        code: 'en-US',
        dateFnsCode: 'enUS',
        derivatives: 'en, en-GB',
        definedBy: 'SYSTEM',
      }}
    />
  </Table>
);

export const UserLocale = () => (
  <Table>
    <LocaleRow
      index={1}
      locale={{
        id: 2,
        name: 'Türkçe',
        code: 'tr-TR',
        dateFnsCode: 'tr',
        derivatives: 'tr',
        definedBy: 'USER',
      }}
    />
  </Table>
);

export const LanguageList = () => (
  <Table>
    <LocaleRow
      index={0}
      locale={{
        id: 1,
        name: 'English',
        code: 'en-US',
        dateFnsCode: 'enUS',
        derivatives: 'en, en-GB',
        definedBy: 'SYSTEM',
      }}
    />
    <LocaleRow
      index={1}
      locale={{
        id: 2,
        name: 'Türkçe',
        code: 'tr-TR',
        dateFnsCode: 'tr',
        derivatives: 'tr',
        definedBy: 'USER',
        selected: true,
      }}
    />
    <LocaleRow
      index={2}
      locale={{
        id: 3,
        name: 'Deutsch',
        code: 'de-DE',
        dateFnsCode: 'de',
        derivatives: 'de, de-AT',
        definedBy: 'USER',
      }}
    />
  </Table>
);

// src/lib/component/rows/LocaleRow.svelte
<tr class:table-active={locale.selected}>
  <th scope="row" class="align-middle">
    {#if locale.definedBy !== 'SYSTEM'}
      <button
        type="button"
        aria-label={$_('buttons.delete')}
        title={$_('buttons.delete')}
        class="btn btn-sm btn-link"
        on:click={onDeleteClick}>
        <i class="fas fa-trash"></i>
      </button>
    {/if}
  </th>
  <td class="align-middle text-nowrap">
    {#if locale.definedBy !== 'SYSTEM'}
      <button class="btn btn-sm btn-link" type="button" on:click={onEditClick}>
        {locale.name}
      </button>
    {:else}
      {locale.name}
    {/if}
  </td>
  <td class="align-middle text-nowrap">{locale.code}</td>
  <td class="align-middle text-nowrap">{locale.dateFnsCode}</td>
  <td class="align-middle text-nowrap">{locale.derivatives}</td>
  <td class="align-middle text-nowrap"
    >{$_('pages.languages.defined-by-options.' + locale.definedBy)}</td>
</tr>

<script>
  import { createEventDispatcher } from 'svelte';
  import { _ } from 'svelte-i18n';

  export let locale;
  export let index;

  const dispatch = createEventDispatcher();

  function onEditClick() {
    dispatch('editClick', { index });
  }

  function onDeleteClick() {
    dispatch('deleteClick', { index });
  }
</script>
