// src/lib/components/badges/CategoryBadge.svelte
<a
  class="badge focus-ring text-decoration-none {category.title === '-'
    ? 'text-bg-primary'
    : 'text-bg-secondary'}"
  title={filterTitle}
  href="{base}/{pageType}?categoryUrl={category.url}">
  {category.title === '-' ? noCategoryText : category.title}
</a>

<script>
  import { _ } from 'svelte-i18n';
  import { base } from '$app/paths';

  export let category;
  export let pageType; // "posts" or "tickets"
  export let filterTitle;
  export let noCategoryText;
</script>

// .design-sync/previews/CategoryBadge.tsx
import * as React from 'react';
import { CategoryBadge } from '@panomc/panel-ui';

export const PostCategory = () => (
  <CategoryBadge
    category={{ title: 'Announcements', url: 'announcements' }}
    pageType="posts"
    filterTitle="Filter posts by this category"
    noCategoryText="No category"
  />
);

export const TicketCategory = () => (
  <CategoryBadge
    category={{ title: 'Ban Appeals', url: 'ban-appeals' }}
    pageType="tickets"
    filterTitle="Filter tickets by this category"
    noCategoryText="No category"
  />
);

export const NoCategory = () => (
  <CategoryBadge
    category={{ title: '-', url: '-' }}
    pageType="posts"
    filterTitle="Filter posts by this category"
    noCategoryText="No category"
  />
);
